version: "3"

services:
  hadoop-master:
    image: bde2020/spark-master:3.0.0-hadoop3.2
    container_name: hadoop-master
    ports:
      - "8080:8080"
      - "7077:7077"
      - "9870:9870"
    environment:
      - INIT_DAEMON_STEP=setup_spark
      - "SPARK_MASTER_PORT=7077"
      - "SPARK_MASTER_WEBUI_PORT=8080"

  hadoop-worker1:
    image: bde2020/spark-worker:3.0.0-hadoop3.2
    container_name: hadoop-worker1
    depends_on:
      - hadoop-master
    ports:
      - "8081:8081"
    environment:
      - "SPARK_MASTER=spark://hadoop-master:7077"

  hadoop-worker2:
    image: bde2020/spark-worker:3.0.0-hadoop3.2
    container_name: hadoop-worker2
    depends_on:
      - hadoop-master
    ports:
      - "8082:8081"
    environment:
      - "SPARK_MASTER=spark://hadoop-master:7077"